---
autoconf-2.69.tar.gz:
  object_id: 088016b1-790d-4bbd-8144-b75583956015
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
  size: 1927468
automake-1.15.tar.gz:
  object_id: 599da939-8df8-4876-ab1b-f6576c2a595b
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
  size: 2244206
fuse-2.9.2.tar.gz:
  object_id: 3194fa81-68be-4b39-bc88-1786b2f95f4a
  sha: fcfc005b1edcd5e8b325729a1b325ff0e8b2a5ab
  size: 560123
fuse-nfs.tar.gz:
  object_id: 0f8fea63-cdd7-413f-83f0-97cb1f73f471
  sha: 1bcdf4552c256167e99058deed3fc8c7b7f22339
  size: 2396160
go1.7.linux-amd64.tar.gz:
  object_id: a4a82ed6-a022-431a-af06-5317422d3211
  sha: a744e29da97fc3aadad1ee0d7d89b0d899645e50
  size: 81573766
libnfs-1.11.0.tar.gz:
  object_id: 737f769d-c0e0-4bf2-a748-bc1aff64c1ff
  sha: b675d6696aa88d0e44f25e9862cf46c1a1fd41f9
  size: 686400
libtool-2.4.6.tar.gz:
  object_id: 04657ae3-fe12-48ad-ab2f-d6ddcb5c96ab
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
  size: 1806697
cf-cli_6.23.1_linux_x86-64.tgz:
  object_id: 53270c4b-ab0d-4f23-ba1b-384e04631c60
  sha: a195e99cae5ab17b453b0a0747508c8f3eee5cae
  size: 6692717
