autoconf-2.69.tar.gz:
  size: 1927468
  object_id: 088016b1-790d-4bbd-8144-b75583956015
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
automake-1.15.tar.gz:
  size: 2244206
  object_id: 599da939-8df8-4876-ab1b-f6576c2a595b
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
berkeleydb/db-5.3.28.tar.gz:
  size: 35090431
  object_id: 3ad9234b-50b7-4f58-7d46-d3569f90d3d6
  sha: fa3f8a41ad5101f43d08bc0efb6241c9b6fc1ae9
fuse-2.9.2.tar.gz:
  size: 560123
  object_id: 3194fa81-68be-4b39-bc88-1786b2f95f4a
  sha: fcfc005b1edcd5e8b325729a1b325ff0e8b2a5ab
fuse-nfs.tar.gz:
  size: 97950
  object_id: 82c7526c-d4e3-40d9-88d3-6925081883bb
  sha: 7d3a9ea3a737e12a4a7512dbaac9c9c6a00cc7bb
go1.10.linux-amd64.tar.gz:
  size: 119905205
  object_id: 5259f8b6-2f58-4738-6502-fd42697cf97d
  sha: 693e2dfd99ef2d608b41c450efd9d277bf2a7f2f
libnfs-1.11.0.tar.gz:
  size: 2590449
  object_id: e5211f5a-a5d9-43ac-a134-402926ae1485
  sha: 6de3ea24278badf40e25457f6178059563c5af89
libtool-2.4.6.tar.gz:
  size: 1806697
  object_id: 04657ae3-fe12-48ad-ab2f-d6ddcb5c96ab
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: 79ec8102-01f0-4e62-7d5a-cac385c29c03
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: d74212ae-15fa-4fbe-57b1-03b5ef1cc663
  sha: 57d69f44f3e058e48a7b79595d36076eb21f5942
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: d666fb5d-2e46-4bb1-6dba-b2e6368c6048
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-debs/nfs-common_1%3a1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: a164c950-3d7a-4747-76c3-d39ef7b0882c
  sha: 38f7234fade7c15ffecf4c043c877b01ead92d3d
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: ae195912-095a-4c3c-5af3-bebd199f2c97
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
openldap/openldap-2.4.44.tgz:
  size: 5658830
  object_id: daea5917-02c3-4fe5-4626-a8805979788d
  sha: 016a738d050a68d388602a74b5e991035cdba149
