berkeleydb/db-5.3.28.tar.gz:
  size: 35090431
  object_id: 3ad9234b-50b7-4f58-7d46-d3569f90d3d6
  sha: fa3f8a41ad5101f43d08bc0efb6241c9b6fc1ae9
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: 79ec8102-01f0-4e62-7d5a-cac385c29c03
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-debs/libevent-2.1-6_2.1.8-stable-4build1_amd64.deb:
  size: 133328
  object_id: c1fc2753-6049-4791-4233-3bb002100204
  sha: sha256:76bc94b3bb4356673c61dd2a4a7b06f40de21dab051aa4b31282aa9d7798b383
nfs-debs/libgssapi-krb5-2_1.15.1-2_amd64.deb:
  size: 120298
  object_id: 00800a67-3797-4f5a-6cf5-e2f8a4290d85
  sha: sha256:07affb4998cbd57d9d125349213cde5a191a5bb466f9085333c87d2a6b252648
nfs-debs/libk5crypto3_1.15.1-2_amd64.deb:
  size: 84942
  object_id: 461520bc-8f33-4c19-7f13-fffa143614cb
  sha: sha256:f52e197b56ddfa20159a9f4967b87dc29a1987ea4a48acd159512761c4ae51e4
nfs-debs/libkrb5-3_1.15.1-2_amd64.deb:
  size: 276254
  object_id: e8d2e2aa-647a-45fd-53f1-b8d1199718b3
  sha: sha256:6613a940c56a785724e330645fd9ac9bf493b849cbb63c541b7a6ce1b426a99d
nfs-debs/libkrb5support0_1.15.1-2_amd64.deb:
  size: 32158
  object_id: 721c58f2-7b41-4736-40f0-9fc36ea629c6
  sha: sha256:da7fd6c191485c6c64b484368a77f3cbbe2d0729f858045ea4182df09f77ba3a
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: d666fb5d-2e46-4bb1-6dba-b2e6368c6048
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-debs/nfs-common_1.3.4-2.1ubuntu4_amd64.deb:
  size: 205360
  object_id: 79011511-3a38-4446-4521-c05ff6ecfc63
  sha: sha256:d241607dacc6c922852e6d7ff7805912ba7cb1f8463e4e23033caac34481456c
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: ae195912-095a-4c3c-5af3-bebd199f2c97
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
openldap/openldap-2.4.44.tgz:
  size: 5658830
  object_id: daea5917-02c3-4fe5-4626-a8805979788d
  sha: 016a738d050a68d388602a74b5e991035cdba149
